sudo: required
services: 
    -docker
script:
    - docker build -t soundaryamangesh/node .
    - docker images soundaryamangesh/node 

before_deploy:
    - docker login -u soundaryamangesh -p Nagendrablock#244

deploy:
    provider: script
    script: docker push soundaryamangesh/node
    on:
        branch: master
